name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   #{ pattern = "*.mirror.e2e.dev", custom_domain = true },
   { pattern = "docker.mirror.e2e.dev", custom_domain = true },
   { pattern = "download-docker-com.mirror.e2e.dev", custom_domain = true },
   { pattern = "quay.mirror.e2e.dev", custom_domain = true },
   { pattern = "gcr.mirror.e2e.dev", custom_domain = true },
   { pattern = "k8s-gcr.mirror.e2e.dev", custom_domain = true },
   { pattern = "k8s.mirror.e2e.dev", custom_domain = true },
   { pattern = "ghcr.mirror.e2e.dev", custom_domain = true },
   { pattern = "cloudsmith.mirror.e2e.dev", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.mirror.e2e.dev", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
